version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Clear cache
          command: rm -rf node_modules/
      - run:
          name: Install
          command: yarn
      - run:
          name: Test
          command: npm test
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Validate build
          command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - unit-test
